/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Omar_Mohamed (https://sketchfab.com/Omar_Mohamed)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/airplane-628232dd846249f6a89ed3fb2e1cd4f5
title: Airplane
*/

import React, { useState } from 'react';
import { useGLTF } from '@react-three/drei';
// import { a } from '@react-spring/three'; // Can't build by webpack issue 

const RAW_URL = `https://raw.githubusercontent.com/${AUTHOR}/${REPO}/${BRANCH}/public`;

const Plane = ({ id, position, rotation }) => {
  const { nodes, materials } = useGLTF(`${RAW_URL}/asset/mesh/plane.gltf`);

  materials['Material.001'].color = {
    r: parseInt(id.slice(0,2), 16) / 256,
    g: parseInt(id.slice(2,4), 16) / 256,
    b: parseInt(id.slice(4,6), 16) / 256,
  }

  const { planeRotation } = {
    planeRotation: [Math.PI / 2, rotation, 0]
  }

  return (
    <group position={position} rotation={planeRotation} scale={0.0075} dispose={null}>
      <group name="RootNode">
        <group name="Cylinder" position={[0, 0, 0]} scale={1}>
          <group name="Cylinder001" position={[0, 0, 1.8]} scale={0.3}>
            <mesh name="Cylinder001_Material005_0" geometry={nodes.Cylinder001_Material005_0.geometry} material={materials['Material.005']} />
            <mesh name="Cylinder001_Material003_0" geometry={nodes.Cylinder001_Material003_0.geometry} material={materials['Material.003']} />
          </group>
          <mesh name="Cylinder_Material003_0" geometry={nodes.Cylinder_Material003_0.geometry} material={materials['Material.003']} />
          <mesh name="Cylinder_Material001_0" geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.001']} />
          <mesh name="Cylinder_Material002_0" geometry={nodes.Cylinder_Material002_0.geometry} material={materials['Material.002']} />
          <mesh name="Cylinder_Material004_0" geometry={nodes.Cylinder_Material004_0.geometry} material={materials['Material.004']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(`${RAW_URL}/asset/mesh/plane.gltf`);
export default Plane;